version: "3.8"

services:
  rocketmq-namesrv:
    image: apache/rocketmq:5.4.0
    container_name: rocketmq-namesrv
    ports:
      - "9876:9876"
    command: sh mqnamesrv

  rocketmq-broker:
    image: apache/rocketmq:5.4.0
    container_name: rocketmq-broker
    depends_on:
      - rocketmq-namesrv
    ports:
      - "10911:10911"
      - "10909:10909"
      - "10912:10912"
    environment:
      - NAMESRV_ADDR=rocketmq-namesrv:9876
    volumes:
      - ./rocketmq/broker.conf:/home/rocketmq/rocketmq-5.4.0/conf/broker.conf
    command: sh mqbroker -n rocketmq-namesrv:9876 -c /home/rocketmq/rocketmq-5.4.0/conf/broker.conf
